spring.application.name=taskflow-api

# ── DataSource ──────────────────────────────────────────────────
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/taskflow}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:taskflow_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:taskflow_pass}
spring.datasource.driver-class-name=org.postgresql.Driver

# ── JPA / Hibernate ─────────────────────────────────────────────
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ── JWT ─────────────────────────────────────────────────────────
jwt.secret=${JWT_SECRET:Placeholder for non docker deployment}
jwt.expiration=${JWT_EXPIRATION:86400000}

# ── Server ──────────────────────────────────────────────────────
server.port=8080

